quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
]

quotes/quotesapp/urls.py
from django.urls import path
from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('tag/', views.tag, name='tag'),
    path('detailQuote/<int:quote_id>', views.detail_quote, name='detail_quote'),
    path('detailAuthor/<int:author_id>', views.detail_author, name='detail_author'),
    path('import_data/', views.import_data, name='import_data'),
]

quotes/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
]

quotes/quotesapp/models.py
from django.db import models

# Create your models here.
# from mongoengine import Document, EmbeddedDocument
# from mongoengine.fields import DateField, StringField,ListField, EmbeddedDocumentField, ReferenceField

class Author(models.Model):
    fullname = models.CharField(max_length=100, null=False)
    born_date = models.DateField(null=True, blank=True)
    born_location = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return f"{self.fullname}"

class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"

class Quote(models.Model):
    quote = models.TextField(null=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.quote}"

quotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput, Textarea, ModelChoiceField, DateField, DateInput, SelectDateWidget, Select, ChoiceField
from .models import Tag, Author, Quote


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=50,
                     required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class AuthorForm(ModelForm):

    fullname = CharField(max_length=100, required=True, widget=TextInput())

    born_date = DateField(
        label="Date of Birth",
        required=True,
        widget=DateInput(format="%Y-%m-%d", attrs={"type": "date"}),
        input_formats=["%Y-%m-%d"]
    )

    born_location = CharField(
        max_length=100, widget=TextInput(), required=False)
    description = CharField(widget=Textarea(), required=False)

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class QuoteForm(ModelForm):

    quote = CharField(required=True, widget=Textarea())

    class Meta:
        model = Quote
        fields = ["quote"]
        exclude = ["tags", "author"]

quotes/quotesapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TagForm, AuthorForm, QuoteForm
from .models import Tag, Author, Quote
from django.contrib import messages
from .web_scraper import new_data
from datetime import datetime
from django.core.paginator import Paginator
from django.http import HttpResponseNotFound


# Create your views here.
def main(request):
    quotes = Quote.objects.order_by('id')
    paginator = Paginator(quotes, 5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, 'quotesapp/index.html', {"page_obj": page_obj})


def detail_quote(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quotesapp/detailQuote.html', {"quote": quote})


def detail_author(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotesapp/detailAuthor.html', {"author": author})


def tag(request):
    if request.user.is_authenticated == False:
        messages.error(request, 'You don\'t have permission to manage tags.')
        return redirect(to='quotesapp:main')

    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/tag.html', {'form': form})
    return render(request, 'quotesapp/tag.html', {'form': TagForm()})


def author(request):
    if request.user.is_authenticated == False:
        messages.error(request, 'You don\'t have permission to manage authors.')
        return redirect(to='quotesapp:main')

    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/author.html', {'form': form})
    return render(request, 'quotesapp/author.html', {'form': AuthorForm()})


def quote(request):
    if request.user.is_authenticated == False:
        messages.error(request, 'You don\'t have permission to manage quotes.')
        return redirect(to='quotesapp:main')

    tags = Tag.objects.all()
    author = Author.objects.all()
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.author = Author.objects.get(fullname=request.POST["author"])
            new_quote.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/quote.html', {"tags": tags, "author": author, 'form': form})
    return render(request, 'quotesapp/quote.html', {"tags": tags, "author": author, 'form': QuoteForm()})


def import_data(request):
    if request.user.is_authenticated == False:
        messages.error(request, 'You don\'t have permission to manage quotes.')
        return redirect(to='quotesapp:main')

    authors, quotes = new_data()
    for author in authors:
        author_object = Author.objects.get_or_create(
            fullname=author["fullname"],
            born_date=datetime.strptime(author["born_date"], "%B %d, %Y").date(),
            born_location=author["born_location"],
            description=author["description"])
        author_object[0].save()
        for quote in quotes:
            quote_object = Quote.objects.get_or_create(
                quote=quote["quote"],
                author=author_object[0])
            for tag in quote["tags"]:
                tag_object = Tag.objects.get_or_create(name=tag)
                quote_object[0].tags.add(tag_object[0])
            quote_object[0].save()

    return redirect(to="quotesapp:main")

quotes/quotesapp/templates/quotesapp/author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPEhtml>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes/quotesapp/templates/quotesapp/detailAuthor.html
{% extends "quotesapp/base.html" %}

{% load extract_tags %}

{% block content %}

<h1>{{author.fullname}}</h1>
<p><b>{{author.born_date}} {{author.born_location}}</b></p>
<p><small>{{author.description}}</small></p>
{% endblock %}

quotes/quotesapp/templates/quotesapp/detailQuote.html
{% extends "quotesapp/base.html" %}

{% load extract_tags %}

{% block content %}

<h1>{{quote.quote}}</h1>
<p>Author: <a href="{% url 'quotesapp:detail_author' quote.author.id %}"> {{ quote.author.fullname }} </a></p>
<p>Tags: <small>
    {{ quote.tags|tags }}
</small></p>
{% endblock %}

quotes/quotesapp/templates/quotesapp/index.html
<!DOCTYPEhtml>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'quotesapp:quote' %}" role="button">Add Quote</a></li>
            <li><a href="{% url 'quotesapp:author' %}" role="button">Add Author</a></li>
            <li><a href="{% url 'quotesapp:tag' %}" role="button">Add Tag</a></li>
            <li><a href="{% url 'quotesapp:import_data' %}" role="button">Import Data</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>

    {% for q in page_obj %}
    <ul>
        <li>
            <a href="{% url 'quotesapp:detail_quote' q.id %}"> {{ q.quote }} </a>
        </li>
    </ul>
    {% endfor %}
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
</main>
</body>
</html>

quotes/quotesapp/templates/quotesapp/quote.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote text:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="author"  required>
                {% for aut in author %}
                <option value="{{aut.fullname}}">{{aut.fullname}}</option>
                {% endfor %}
            </select>
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quotesapp/templates/quotesapp/tag.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}